import { render, screen } from '@testing-library/react';

import Home from './Home/Home';
import userEvent from '@testing-library/user-event';

import { rest } from 'msw';
import { setupServer } from 'msw/node';

const mockResponse = [
  {
    id: 1,
    'file-name': 'ant00',
    name: {
      'name-USen': 'Cyrano',
      'name-EUen': 'Cyrano',
      'name-EUde': 'Theo',
      'name-EUes': 'Cirano',
      'name-USes': 'Cirano',
      'name-EUfr': 'Cyrano',
      'name-USfr': 'Cyrano',
      'name-EUit': 'Cirano',
      'name-EUnl': 'Cyrano',
      'name-CNzh': '阳明',
      'name-TWzh': '陽明',
      'name-JPja': 'さくらじま',
      'name-KRko': '사지마',
      'name-EUru': 'Сирано',
    },
    personality: 'Cranky',
    'birthday-string': 'March 9th',
    birthday: '9/3',
    species: 'Anteater',
    gender: 'Male',
    subtype: 'B',
    hobby: 'Education',
    'catch-phrase': 'ah-CHOO',
    icon_uri: 'https://acnhapi.com/v1/icons/villagers/1',
    image_uri: 'https://acnhapi.com/v1/images/villagers/1',
    'bubble-color': '#194c89',
    'text-color': '#fffad4',
    saying: "Don't punch your nose to spite your face.",
    'catch-translations': {
      'catch-USen': 'ah-CHOO',
      'catch-EUen': 'ah-CHOO',
      'catch-EUde': 'schneuf',
      'catch-EUes': 'achús',
      'catch-USes': 'achús',
      'catch-EUfr': 'ATCHOUM',
      'catch-USfr': 'ATCHOUM',
      'catch-EUit': 'ett-CCIÙ',
      'catch-EUnl': 'ha-TSJOE',
      'catch-CNzh': '有的',
      'catch-TWzh': '有的',
      'catch-JPja': 'でごわす',
      'catch-KRko': '임돠',
      'catch-EUru': 'апчхи',
    },
  },
  {
    id: 2,
    'file-name': 'ant01',
    name: {
      'name-USen': 'Antonio',
      'name-EUen': 'Antonio',
      'name-EUde': 'Siggi',
      'name-EUes': 'Antonio',
      'name-USes': 'Antonio',
      'name-EUfr': 'Antonio',
      'name-USfr': 'Antonio',
      'name-EUit': 'Antonio',
      'name-EUnl': 'Antonio',
      'name-CNzh': '阿诚',
      'name-TWzh': '阿誠',
      'name-JPja': 'マコト',
      'name-KRko': '퍼머거',
      'name-EUru': 'Антонио',
    },
    personality: 'Jock',
    'birthday-string': 'October 20th',
    birthday: '20/10',
    species: 'Anteater',
    gender: 'Male',
    subtype: 'B',
    hobby: 'Fitness',
    'catch-phrase': 'honk',
    icon_uri: 'https://acnhapi.com/v1/icons/villagers/2',
    image_uri: 'https://acnhapi.com/v1/images/villagers/2',
    'bubble-color': '#fff98f',
    'text-color': '#879b96',
    saying: 'Always go for the burn!',
    'catch-translations': {
      'catch-USen': 'honk',
      'catch-EUen': 'honk',
      'catch-EUde': 'schlürrrf',
      'catch-EUes': 'fufuf',
      'catch-USes': 'fufuf',
      'catch-EUfr': 'pouet',
      'catch-USfr': 'pouet',
      'catch-EUit': 'honk',
      'catch-EUnl': 'snuit',
      'catch-CNzh': '真诚',
      'catch-TWzh': '真誠',
      'catch-JPja': 'ホントに',
      'catch-KRko': '진짜로',
      'catch-EUru': 'го-го-го',
    },
  },
  {
    id: 3,
    'file-name': 'ant02',
    name: {
      'name-USen': 'Pango',
      'name-EUen': 'Pango',
      'name-EUde': 'Mathilda',
      'name-EUes': 'Aspidora',
      'name-USes': 'Aspidora',
      'name-EUfr': 'Mathilda',
      'name-USfr': 'Mathilda',
      'name-EUit': 'Carlotta',
      'name-EUnl': 'Pango',
      'name-CNzh': '佩希',
      'name-TWzh': '佩希',
      'name-JPja': 'パトラ',
      'name-KRko': '패트라',
      'name-EUru': 'Панго',
    },
    personality: 'Peppy',
    'birthday-string': 'November 9th',
    birthday: '9/11',
    species: 'Anteater',
    gender: 'Female',
    subtype: 'B',
    hobby: 'Fashion',
    'catch-phrase': 'snooooof',
    icon_uri: 'https://acnhapi.com/v1/icons/villagers/3',
    image_uri: 'https://acnhapi.com/v1/images/villagers/3',
    'bubble-color': '#00d1bd',
    'text-color': '#fffce9',
    saying: 'A thing of beauty is a joy forever.',
    'catch-translations': {
      'catch-USen': 'snooooof',
      'catch-EUen': 'snooooof',
      'catch-EUde': 'schnieef',
      'catch-EUes': 'snuf-snuf',
      'catch-USes': 'snuf-snuf',
      'catch-EUfr': 'pouuuuuf',
      'catch-USfr': 'pouuuuuf',
      'catch-EUit': 'snuuf',
      'catch-EUnl': 'snufffff',
      'catch-CNzh': '希希',
      'catch-TWzh': '希希',
      'catch-JPja': 'だっしー',
      'catch-KRko': '라지요',
      'catch-EUru': 'снуф-снуф',
    },
  },
  {
    id: 4,
    'file-name': 'ant03',
    name: {
      'name-USen': 'Anabelle',
      'name-EUen': 'Anabelle',
      'name-EUde': 'Annabell',
      'name-EUes': 'Anabel',
      'name-USes': 'Anabel',
      'name-EUfr': 'Anabelle',
      'name-USfr': 'Anabelle',
      'name-EUit': 'Annalisa',
      'name-EUnl': 'Anabelle',
      'name-CNzh': '有美',
      'name-TWzh': '有美',
      'name-JPja': 'あるみ',
      'name-KRko': '아롱이',
      'name-EUru': 'Анабель',
    },
    personality: 'Peppy',
    'birthday-string': 'February 16th',
    birthday: '16/2',
    species: 'Anteater',
    gender: 'Female',
    subtype: 'B',
    hobby: 'Fashion',
    'catch-phrase': 'snorty',
    icon_uri: 'https://acnhapi.com/v1/icons/villagers/4',
    image_uri: 'https://acnhapi.com/v1/images/villagers/4',
    'bubble-color': '#ff791f',
    'text-color': '#fff2bb',
    saying: "Dance like no one's watching!",
    'catch-translations': {
      'catch-USen': 'snorty',
      'catch-EUen': 'snorty',
      'catch-EUde': 'puuust',
      'catch-EUes': 'esnoink',
      'catch-USes': 'fa-fiú',
      'catch-EUfr': 'grognon',
      'catch-USfr': 'grognon',
      'catch-EUit': 'snorty',
      'catch-EUnl': 'snork',
      'catch-CNzh': '真的假的',
      'catch-TWzh': '真的假的',
      'catch-JPja': 'マジでー',
      'catch-KRko': '정말',
      'catch-EUru': 'хрум-хрум',
    },
  },
  {
    id: 5,
    'file-name': 'ant06',
    name: {
      'name-USen': 'Snooty',
      'name-EUen': 'Snooty',
      'name-EUde': 'Hilde',
      'name-EUes': 'Rosanari',
      'name-USes': 'Rosanari',
      'name-EUfr': 'Tarina',
      'name-USfr': 'Tarina',
      'name-EUit': 'Lucrezia',
      'name-EUnl': 'Snooty',
      'name-CNzh': '贵妃',
      'name-TWzh': '貴妃',
      'name-JPja': 'こまち',
      'name-KRko': '스누티',
      'name-EUru': 'Снути',
    },
    personality: 'Snooty',
    'birthday-string': 'October 24th',
    birthday: '24/10',
    species: 'Anteater',
    gender: 'Female',
    subtype: 'A',
    hobby: 'Education',
    'catch-phrase': 'sniffff',
    icon_uri: 'https://acnhapi.com/v1/icons/villagers/5',
    image_uri: 'https://acnhapi.com/v1/images/villagers/5',
    'bubble-color': '#f2bdc7',
    'text-color': '#634b4b',
    saying: 'Request forgiveness, not permission.',
    'catch-translations': {
      'catch-USen': 'sniffff',
      'catch-EUen': 'sniffff',
      'catch-EUde': 'schnuff',
      'catch-EUes': 'sniff',
      'catch-USes': 'sniff',
      'catch-EUfr': 'snif snif',
      'catch-USfr': 'snif snif',
      'catch-EUit': 'sniffff',
      'catch-EUnl': 'snuifff',
      'catch-CNzh': '麻烦了',
      'catch-TWzh': '麻煩了',
      'catch-JPja': 'たもれ',
      'catch-KRko': '추릅',
      'catch-EUru': 'шмыг',
    },
  },
  {
    id: 6,
    'file-name': 'ant08',
    name: {
      'name-USen': 'Annalisa',
      'name-EUen': 'Annalisa',
      'name-EUde': 'Annalena',
      'name-EUes': 'Alba',
      'name-USes': 'Alba',
      'name-EUfr': 'Roberta',
      'name-USfr': 'Roberta',
      'name-EUit': 'Anita',
      'name-EUnl': 'Annalisa',
      'name-CNzh': '小雅',
      'name-TWzh': '小雅',
      'name-JPja': 'みやび',
      'name-KRko': '설백',
      'name-EUru': 'Аннализа',
    },
    personality: 'Normal',
    'birthday-string': 'February 6th',
    birthday: '6/2',
    species: 'Anteater',
    gender: 'Female',
    subtype: 'A',
    hobby: 'Nature',
    'catch-phrase': 'gumdrop',
    icon_uri: 'https://acnhapi.com/v1/icons/villagers/6',
    image_uri: 'https://acnhapi.com/v1/images/villagers/6',
    'bubble-color': '#ffffff',
    'text-color': '#848484',
    saying: 'Home is where the heart is.',
    'catch-translations': {
      'catch-USen': 'gumdrop',
      'catch-EUen': 'gumdrop',
      'catch-EUde': 'schnüffel',
      'catch-EUes': 'nubecillas',
      'catch-USes': 'snifffi',
      'catch-EUfr': 'tap tap',
      'catch-USfr': 'tap tap',
      'catch-EUit': 'chic',
      'catch-EUnl': 'dropje',
      'catch-CNzh': '优雅',
      'catch-TWzh': '優雅',
      'catch-JPja': 'をかし',
      'catch-KRko': '하양하양',
      'catch-EUru': 'жуй-жуй',
    },
  },
  {
    id: 7,
    'file-name': 'ant09',
    name: {
      'name-USen': 'Olaf',
      'name-EUen': 'Olaf',
      'name-EUde': 'Olaf',
      'name-EUes': 'Olaf',
      'name-USes': 'Olaf',
      'name-EUfr': 'Blair',
      'name-USfr': 'Blair',
      'name-EUit': 'Ettore',
      'name-EUnl': 'Olaf',
      'name-CNzh': '安东尼',
      'name-TWzh': '安東尼',
      'name-JPja': 'アントニオ',
      'name-KRko': '안토니오',
      'name-EUru': 'Олаф',
    },
    personality: 'Smug',
    'birthday-string': 'May 19th',
    birthday: '19/5',
    species: 'Anteater',
    gender: 'Male',
    subtype: 'A',
    hobby: 'Education',
    'catch-phrase': 'whiffa',
    icon_uri: 'https://acnhapi.com/v1/icons/villagers/7',
    image_uri: 'https://acnhapi.com/v1/images/villagers/7',
    'bubble-color': '#ff791f',
    'text-color': '#fff2bb',
    saying: 'Keep your nose clean.',
    'catch-translations': {
      'catch-USen': 'whiffa',
      'catch-EUen': 'whiffa',
      'catch-EUde': 'mwahaaa',
      'catch-EUes': 'fruf',
      'catch-USes': 'fruf',
      'catch-EUfr': 'tartarin',
      'catch-USfr': 'yesss',
      'catch-EUit': 'swish',
      'catch-EUnl': 'toet',
      'catch-CNzh': '欧啦',
      'catch-TWzh': '歐啦',
      'catch-JPja': 'ムーチョ',
      'catch-KRko': '무쵸',
      'catch-EUru': 'уф-уф',
    },
  },
  {
    id: 8,
    'file-name': 'bea00',
    name: {
      'name-USen': 'Teddy',
      'name-EUen': 'Teddy',
      'name-EUde': 'Torsten',
      'name-EUes': 'Teddy',
      'name-USes': 'Teddy',
      'name-EUfr': 'Teddy',
      'name-USfr': 'Teddy',
      'name-EUit': 'Teddy',
      'name-EUnl': 'Teddy',
      'name-CNzh': '太平',
      'name-TWzh': '太平',
      'name-JPja': 'たいへいた',
      'name-KRko': '병태',
      'name-EUru': 'Тедди',
    },
    personality: 'Jock',
    'birthday-string': 'September 26th',
    birthday: '26/9',
    species: 'Bear',
    gender: 'Male',
    subtype: 'B',
    hobby: 'Fitness',
    'catch-phrase': 'grooof',
    icon_uri: 'https://acnhapi.com/v1/icons/villagers/8',
    image_uri: 'https://acnhapi.com/v1/images/villagers/8',
    'bubble-color': '#ff791f',
    'text-color': '#fff2bb',
    saying: 'No pain, no gain!',
    'catch-translations': {
      'catch-USen': 'grooof',
      'catch-EUen': 'grooof',
      'catch-EUde': 'gruff',
      'catch-EUes': 'gruuuf',
      'catch-USes': 'gruuuf',
      'catch-EUfr': 'grrrrrr',
      'catch-USfr': 'grrrrrr',
      'catch-EUit': 'gruf',
      'catch-EUnl': 'grommm',
      'catch-CNzh': '太好了',
      'catch-TWzh': '太好了',
      'catch-JPja': 'ですたい',
      'catch-KRko': '입네다',
      'catch-EUru': 'быр-быр',
    },
  },
  {
    id: 9,
    'file-name': 'bea01',
    name: {
      'name-USen': 'Pinky',
      'name-EUen': 'Pinky',
      'name-EUde': 'Pia',
      'name-EUes': 'Violeta',
      'name-USes': 'Violeta',
      'name-EUfr': 'Rosine',
      'name-USfr': 'Rosine',
      'name-EUit': 'Pinky',
      'name-EUnl': 'Pinky',
      'name-CNzh': '丹丹',
      'name-TWzh': '丹丹',
      'name-JPja': 'タンタン',
      'name-KRko': '링링',
      'name-EUru': 'Пинки',
    },
    personality: 'Peppy',
    'birthday-string': 'September 9th',
    birthday: '9/9',
    species: 'Bear',
    gender: 'Female',
    subtype: 'B',
    hobby: 'Fashion',
    'catch-phrase': 'wah',
    icon_uri: 'https://acnhapi.com/v1/icons/villagers/9',
    image_uri: 'https://acnhapi.com/v1/images/villagers/9',
    'bubble-color': '#fff98f',
    'text-color': '#879b96',
    saying: 'Time spent with friends is time well spent.',
    'catch-translations': {
      'catch-USen': 'wah',
      'catch-EUen': 'wah',
      'catch-EUde': 'schätzchen',
      'catch-EUes': 'terronillo',
      'catch-USes': 'guah',
      'catch-EUfr': 'ouah',
      'catch-USfr': 'ouah',
      'catch-EUit': 'cubetto',
      'catch-EUnl': 'wauw',
      'catch-CNzh': '哇喔',
      'catch-TWzh': '哇喔',
      'catch-JPja': 'わぉ',
      'catch-KRko': '와',
      'catch-EUru': 'ну и ну',
    },
  },
  {
    id: 10,
    'file-name': 'bea02',
    name: {
      'name-USen': 'Curt',
      'name-EUen': 'Curt',
      'name-EUde': 'Kurt',
      'name-EUes': 'Gorbaché',
      'name-USes': 'Gorbaché',
      'name-EUfr': 'Curt',
      'name-USfr': 'Curt',
      'name-EUit': 'Curt',
      'name-EUnl': 'Curt',
      'name-CNzh': '铁熊',
      'name-TWzh': '鐵熊',
      'name-JPja': 'ガンテツ',
      'name-KRko': '뚝심',
      'name-EUru': 'Керт',
    },
    personality: 'Cranky',
    'birthday-string': 'July 1st',
    birthday: '1/7',
    species: 'Bear',
    gender: 'Male',
    subtype: 'A',
    hobby: 'Nature',
    'catch-phrase': 'fuzzball',
    icon_uri: 'https://acnhapi.com/v1/icons/villagers/10',
    image_uri: 'https://acnhapi.com/v1/images/villagers/10',
    'bubble-color': '#515151',
    'text-color': '#fffce9',
    saying: 'A Bell saved is a Bell earned.',
    'catch-translations': {
      'catch-USen': 'fuzzball',
      'catch-EUen': 'fuzzball',
      'catch-EUde': 'grumml',
      'catch-EUes': 'oye',
      'catch-USes': 'gromp',
      'catch-EUfr': 'bouboule',
      'catch-USfr': 'bouboule',
      'catch-EUit': 'grrroan',
      'catch-EUnl': 'brombeer',
      'catch-CNzh': '嗯唔',
      'catch-TWzh': '嗯唔',
      'catch-JPja': 'ウム',
      'catch-KRko': '음',
      'catch-EUru': 'махрово',
    },
  },
  {
    id: 11,
    'file-name': 'bea03',
    name: {
      'name-USen': 'Chow',
      'name-EUen': 'Chow',
      'name-EUde': 'Chang',
      'name-EUes': 'Pando',
      'name-USes': 'Pando',
      'name-EUfr': 'Chulin',
      'name-USfr': 'Chulin',
      'name-EUit': 'Chowchow',
      'name-EUnl': 'Chow',
      'name-CNzh': '朝阳',
      'name-TWzh': '朝陽',
      'name-JPja': 'チャウヤン',
      'name-KRko': '츄양',
      'name-EUru': 'Чау',
    },
    personality: 'Cranky',
    'birthday-string': 'July 22nd',
    birthday: '22/7',
    species: 'Bear',
    gender: 'Male',
    subtype: 'B',
    hobby: 'Fitness',
    'catch-phrase': 'aiya',
    icon_uri: 'https://acnhapi.com/v1/icons/villagers/11',
    image_uri: 'https://acnhapi.com/v1/images/villagers/11',
    'bubble-color': '#f2bdc7',
    'text-color': '#634b4b',
    saying: 'All good things must come to an end.',
    'catch-translations': {
      'catch-USen': 'aiya',
      'catch-EUen': 'aiya',
      'catch-EUde': 'hiijaa',
      'catch-EUes': 'ándale-oso',
      'catch-USes': 'grinchu',
      'catch-EUfr': 'lala',
      'catch-USfr': 'lala',
      'catch-EUit': 'ehilà',
      'catch-EUnl': 'kiai',
      'catch-CNzh': '有喔',
      'catch-TWzh': '有喔',
      'catch-JPja': 'アルヨ',
      'catch-KRko': '그럼',
      'catch-EUru': 'ай-яй',
    },
  },
  {
    id: 12,
    'file-name': 'bea05',
    name: {
      'name-USen': 'Nate',
      'name-EUen': 'Nate',
      'name-EUde': 'Nathan',
      'name-EUes': 'Nachete',
      'name-USes': 'Nachete',
      'name-EUfr': 'Nathan',
      'name-USfr': 'Nathan',
      'name-EUit': 'Gianni',
      'name-EUnl': 'Nate',
      'name-CNzh': '巴克思',
      'name-TWzh': '巴克思',
      'name-JPja': 'バッカス',
      'name-KRko': '박하스',
      'name-EUru': 'Нэйт',
    },
    personality: 'Lazy',
    'birthday-string': 'August 16th',
    birthday: '16/8',
    species: 'Bear',
    gender: 'Male',
    subtype: 'B',
    hobby: 'Play',
    'catch-phrase': 'yawwwn',
    icon_uri: 'https://acnhapi.com/v1/icons/villagers/12',
    image_uri: 'https://acnhapi.com/v1/images/villagers/12',
    'bubble-color': '#e8b010',
    'text-color': '#fffce9',
    saying: 'Be true to yourself.',
    'catch-translations': {
      'catch-USen': 'yawwwn',
      'catch-EUen': 'yawwwn',
      'catch-EUde': 'gäähn',
      'catch-EUes': 'uuaaaah',
      'catch-USes': 'uuaaaah',
      'catch-EUfr': 'baaîîîllle',
      'catch-USfr': 'baaîîîllle',
      'catch-EUit': 'yauuun',
      'catch-EUnl': 'gaaaap',
      'catch-CNzh': '嗯是',
      'catch-TWzh': '嗯是',
      'catch-JPja': 'んだ',
      'catch-KRko': '힘내',
      'catch-EUru': 'спа-а-ать',
    },
  },
  {
    id: 13,
    'file-name': 'bea06',
    name: {
      'name-USen': 'Groucho',
      'name-EUen': 'Groucho',
      'name-EUde': 'Ernst',
      'name-EUes': 'Groucho',
      'name-USes': 'Groucho',
      'name-EUfr': 'Ronchon',
      'name-USfr': 'Ronchon',
      'name-EUit': 'Groucho',
      'name-EUnl': 'Groucho',
      'name-CNzh': '爪爪',
      'name-TWzh': '爪爪',
      'name-JPja': 'クロー',
      'name-KRko': '거무틱',
      'name-EUru': 'Граучо',
    },
    personality: 'Cranky',
    'birthday-string': 'October 23rd',
    birthday: '23/10',
    species: 'Bear',
    gender: 'Male',
    subtype: 'B',
    hobby: 'Music',
    'catch-phrase': 'grumble',
    icon_uri: 'https://acnhapi.com/v1/icons/villagers/13',
    image_uri: 'https://acnhapi.com/v1/images/villagers/13',
    'bubble-color': '#194c89',
    'text-color': '#fffad4',
    saying: 'Rocky road is more than just a flavor of ice cream.',
    'catch-translations': {
      'catch-USen': 'grumble',
      'catch-EUen': 'grumble',
      'catch-EUde': 'brummel',
      'catch-EUes': 'jorrr',
      'catch-USes': 'jorrr',
      'catch-EUfr': 'grou-gnon',
      'catch-USfr': 'grou-gnon',
      'catch-EUit': 'grum grum',
      'catch-EUnl': 'brom',
      'catch-CNzh': '哇哇',
      'catch-TWzh': '哇哇',
      'catch-JPja': 'ワォー',
      'catch-KRko': '어쩌라구',
      'catch-EUru': 'бур-бур',
    },
  },
  {
    id: 14,
    'file-name': 'bea07',
    name: {
      'name-USen': 'Tutu',
      'name-EUen': 'Tutu',
      'name-EUde': 'Mandy',
      'name-EUes': 'Tutú',
      'name-USes': 'Tutú',
      'name-EUfr': 'Tutu',
      'name-USfr': 'Tutu',
      'name-EUit': 'Lola',
      'name-EUnl': 'Tutu',
      'name-CNzh': '恋恋',
      'name-TWzh': '戀戀',
      'name-JPja': 'れんにゅう',
      'name-KRko': '연유',
      'name-EUru': 'Туту',
    },
    personality: 'Peppy',
    'birthday-string': 'September 15th',
    birthday: '15/9',
    species: 'Bear',
    gender: 'Female',
    subtype: 'B',
    hobby: 'Fashion',
    'catch-phrase': 'twinkles',
    icon_uri: 'https://acnhapi.com/v1/icons/villagers/14',
    image_uri: 'https://acnhapi.com/v1/images/villagers/14',
    'bubble-color': '#ffffff',
    'text-color': '#848484',
    saying: 'Even the best of friends start out as strangers.',
    'catch-translations': {
      'catch-USen': 'twinkles',
      'catch-EUen': 'twinkles',
      'catch-EUde': 'hooonig',
      'catch-EUes': 'fisflash',
      'catch-USes': 'fisflash',
      'catch-EUfr': 'pic pic',
      'catch-USfr': 'pic pic',
      'catch-EUit': 'gnifa',
      'catch-EUnl': 'honingbij',
      'catch-CNzh': '加油',
      'catch-TWzh': '加油',
      'catch-JPja': 'ファイト',
      'catch-KRko': '사르르',
      'catch-EUru': 'ме-е-ед',
    },
  },
  {
    id: 15,
    'file-name': 'bea08',
    name: {
      'name-USen': 'Ursala',
      'name-EUen': 'Ursala',
      'name-EUde': 'Ursula',
      'name-EUes': 'Úrsula',
      'name-USes': 'Úrsula',
      'name-EUfr': 'Oursula',
      'name-USfr': 'Oursula',
      'name-EUit': 'Ursula',
      'name-EUnl': 'Ursala',
      'name-CNzh': '妮雅',
      'name-TWzh': '妮雅',
      'name-JPja': 'ネーヤ',
      'name-KRko': '네이아',
      'name-EUru': 'Урсала',
    },
    personality: 'Uchi',
    'birthday-string': 'January 16th',
    birthday: '16/1',
    species: 'Bear',
    gender: 'Female',
    subtype: 'A',
    hobby: 'Music',
    'catch-phrase': 'grooomph',
    icon_uri: 'https://acnhapi.com/v1/icons/villagers/15',
    image_uri: 'https://acnhapi.com/v1/images/villagers/15',
    'bubble-color': '#f2bdc7',
    'text-color': '#634b4b',
    saying: 'Surround yourself with things you love.',
    'catch-translations': {
      'catch-USen': 'grooomph',
      'catch-EUen': 'grooomph',
      'catch-EUde': 'brumbrum',
      'catch-EUes': 'grumf',
      'catch-USes': 'grumf',
      'catch-EUfr': 'groumpf',
      'catch-USfr': 'groumpf',
      'catch-EUit': 'gruuunf',
      'catch-EUnl': 'oemf',
      'catch-CNzh': '呀呐',
      'catch-TWzh': '呀吶',
      'catch-JPja': 'やーねぇ',
      'catch-KRko': '그라지',
      'catch-EUru': 'гррум',
    },
  },
  {
    id: 16,
    'file-name': 'bea09',
    name: {
      'name-USen': 'Grizzly',
      'name-EUen': 'Grizzly',
      'name-EUde': 'Gerald',
      'name-EUes': 'Gruñón',
      'name-USes': 'Gruñón',
      'name-EUfr': 'Grizzly',
      'name-USfr': 'Grizzly',
      'name-EUit': 'Grizzly',
      'name-EUnl': 'Grizzly',
      'name-CNzh': '穆穆',
      'name-TWzh': '穆穆',
      'name-JPja': 'ムー',
      'name-KRko': '무뚝',
      'name-EUru': 'Гризли',
    },
    personality: 'Cranky',
    'birthday-string': 'July 31st',
    birthday: '31/7',
    species: 'Bear',
    gender: 'Male',
    subtype: 'B',
    hobby: 'Education',
    'catch-phrase': 'grrr',
    icon_uri: 'https://acnhapi.com/v1/icons/villagers/16',
    image_uri: 'https://acnhapi.com/v1/images/villagers/16',
    'bubble-color': '#7c6559',
    'text-color': '#eac113',
    saying: "Those who live in glass houses shouldn't throw stones.",
    'catch-translations': {
      'catch-USen': 'grrr',
      'catch-EUen': 'grrr',
      'catch-EUde': 'grrr',
      'catch-EUes': 'tostón',
      'catch-USes': 'grrre',
      'catch-EUfr': 'canaillou',
      'catch-USfr': 'canaillou',
      'catch-EUit': 'grrr',
      'catch-EUnl': 'grrr',
      'catch-CNzh': '熊熊',
      'catch-TWzh': '熊熊',
      'catch-JPja': 'だクマ',
      'catch-KRko': '냅둬',
      'catch-EUru': 'грр',
    },
  },
  {
    id: 17,
    'file-name': 'bea10',
    name: {
      'name-USen': 'Paula',
      'name-EUen': 'Paula',
      'name-EUde': 'Paula',
      'name-EUes': 'Lizi',
      'name-USes': 'Lizi',
      'name-EUfr': 'Wendy',
      'name-USfr': 'Wendy',
      'name-EUit': 'Bruna',
      'name-EUnl': 'Paula',
      'name-CNzh': '瑞秋',
      'name-TWzh': '瑞秋',
      'name-JPja': 'レイチェル',
      'name-KRko': '레이첼',
      'name-EUru': 'Паула',
    },
    personality: 'Uchi',
    'birthday-string': 'March 22nd',
    birthday: '22/3',
    species: 'Bear',
    gender: 'Female',
    subtype: 'B',
    hobby: 'Fitness',
    'catch-phrase': 'yodelay',
    icon_uri: 'https://acnhapi.com/v1/icons/villagers/17',
    image_uri: 'https://acnhapi.com/v1/images/villagers/17',
    'bubble-color': '#e8b010',
    'text-color': '#fffce9',
    saying: 'Trends always make a comeback.',
    'catch-translations': {
      'catch-USen': 'yodelay',
      'catch-EUen': 'yodelay',
      'catch-EUde': 'bralala',
      'catch-EUes': 'borobó',
      'catch-USes': 'borobó',
      'catch-EUfr': 'léchouille',
      'catch-USfr': 'tourlou',
      'catch-EUit': 'bah',
      'catch-EUnl': 'jodelie',
      'catch-CNzh': '耶呼',
      'catch-TWzh': '耶呼',
      'catch-JPja': 'ヤッホー',
      'catch-KRko': '야호야호',
      'catch-EUru': 'йодль',
    },
  },
  {
    id: 18,
    'file-name': 'bea11',
    name: {
      'name-USen': 'Ike',
      'name-EUen': 'Ike',
      'name-EUde': 'Ike',
      'name-EUes': 'Astillas',
      'name-USes': 'Astillas',
      'name-EUfr': 'Isaac',
      'name-USfr': 'Isaac',
      'name-EUit': 'Ortensio',
      'name-EUnl': 'Ike',
      'name-CNzh': '大功',
      'name-TWzh': '大功',
      'name-JPja': 'ダイク',
      'name-KRko': '대공',
      'name-EUru': 'Айк',
    },
    personality: 'Cranky',
    'birthday-string': 'May 16th',
    birthday: '16/5',
    species: 'Bear',
    gender: 'Male',
    subtype: 'A',
    hobby: 'Nature',
    'catch-phrase': 'roadie',
    icon_uri: 'https://acnhapi.com/v1/icons/villagers/18',
    image_uri: 'https://acnhapi.com/v1/images/villagers/18',
    'bubble-color': '#4c3317',
    'text-color': '#fffce9',
    saying: 'The higher you climb, the smaller things look.',
    'catch-translations': {
      'catch-USen': 'roadie',
      'catch-EUen': 'roadie',
      'catch-EUde': 'brrruah',
      'catch-EUes': 'tornillos',
      'catch-USes': 'grurrr',
      'catch-EUfr': "pot d'miel",
      'catch-USfr': "pot d'miel",
      'catch-EUit': 'sgrugno',
      'catch-EUnl': 'ja denk',
      'catch-CNzh': '施主',
      'catch-TWzh': '施主',
      'catch-JPja': 'ボウズ',
      'catch-KRko': '터프',
      'catch-EUru': 'гарр-сон',
    },
  },
  {
    id: 19,
    'file-name': 'bea12',
    name: {
      'name-USen': 'Charlise',
      'name-EUen': 'Charlise',
      'name-EUde': 'Tabea',
      'name-EUes': 'Charo',
      'name-USes': 'Charo',
      'name-EUfr': 'Zabou',
      'name-USfr': 'Zabou',
      'name-EUit': 'Orsola',
      'name-EUnl': 'Charlise',
      'name-CNzh': '恰咪',
      'name-TWzh': '恰咪',
      'name-JPja': 'チャーミー',
      'name-KRko': '챠미',
      'name-EUru': 'Шарлиз',
    },
    personality: 'Uchi',
    'birthday-string': 'April 17th',
    birthday: '17/4',
    species: 'Bear',
    gender: 'Female',
    subtype: 'B',
    hobby: 'Fitness',
    'catch-phrase': 'urgh',
    icon_uri: 'https://acnhapi.com/v1/icons/villagers/19',
    image_uri: 'https://acnhapi.com/v1/images/villagers/19',
    'bubble-color': '#78dd62',
    'text-color': '#28665a',
    saying: 'Actions speak louder than words.',
    'catch-translations': {
      'catch-USen': 'urgh',
      'catch-EUen': 'urgh',
      'catch-EUde': 'bärbär',
      'catch-EUes': 'comolooyes',
      'catch-USes': 'urrrgh',
      'catch-EUfr': 'verlue',
      'catch-USfr': 'chacha',
      'catch-EUit': 'sbuff',
      'catch-EUnl': 'pff',
      'catch-CNzh': '唷咻',
      'catch-TWzh': '唷咻',
      'catch-JPja': 'よいしょ',
      'catch-KRko': '으랏차차',
      'catch-EUru': 'ого-го',
    },
  },
  {
    id: 20,
    'file-name': 'bea13',
    name: {
      'name-USen': 'Beardo',
      'name-EUen': 'Beardo',
      'name-EUde': 'Berthold',
      'name-EUes': 'Bernabé',
      'name-USes': 'Bernabé',
      'name-EUfr': 'Eustache',
      'name-USfr': 'Eustache',
      'name-EUit': 'Barnaba',
      'name-EUnl': 'Beardo',
      'name-CNzh': '熊大叔',
      'name-TWzh': '熊大叔',
      'name-JPja': 'ベアード',
      'name-KRko': '베어드',
      'name-EUru': 'Беардо',
    },
    personality: 'Smug',
    'birthday-string': 'September 27th',
    birthday: '27/9',
    species: 'Bear',
    gender: 'Male',
    subtype: 'A',
    hobby: 'Education',
    'catch-phrase': 'whiskers',
    icon_uri: 'https://acnhapi.com/v1/icons/villagers/20',
    image_uri: 'https://acnhapi.com/v1/images/villagers/20',
    'bubble-color': '#3fd8e0',
    'text-color': '#fffce9',
    saying: 'Fashion first!',
    'catch-translations': {
      'catch-USen': 'whiskers',
      'catch-EUen': 'whiskers',
      'catch-EUde': 'brrroho',
      'catch-EUes': 'bigotre',
      'catch-USes': 'bigotre',
      'catch-EUfr': 'poilodos',
      'catch-USfr': 'ciao',
      'catch-EUit': 'andale',
      'catch-EUnl': 'snorhaar',
      'catch-CNzh': '咳咳',
      'catch-TWzh': '咳咳',
      'catch-JPja': 'オッホン',
      'catch-KRko': '오홍홍',
      'catch-EUru': 'усы мои',
    },
  },
  {
    id: 21,
    'file-name': 'bea14',
    name: {
      'name-USen': 'Klaus',
      'name-EUen': 'Klaus',
      'name-EUde': 'Grischa',
      'name-EUes': 'Gruñerto',
      'name-USes': 'Gruñerto',
      'name-EUfr': 'Klaus',
      'name-USfr': 'Klaus',
      'name-EUit': 'Maciste',
      'name-EUnl': 'Klaus',
      'name-CNzh': '熊战士',
      'name-TWzh': '熊戰士',
      'name-JPja': 'クマロス',
      'name-KRko': '곰도로스',
      'name-EUru': 'Клаус',
    },
    personality: 'Smug',
    'birthday-string': 'March 31st',
    birthday: '31/3',
    species: 'Bear',
    gender: 'Male',
    subtype: 'A',
    hobby: 'Education',
    'catch-phrase': 'strudel',
    icon_uri: 'https://acnhapi.com/v1/icons/villagers/21',
    image_uri: 'https://acnhapi.com/v1/images/villagers/21',
    'bubble-color': '#acc8cf',
    'text-color': '#498992',
    saying: 'Pride goes before a fall.',
    'catch-translations': {
      'catch-USen': 'strudel',
      'catch-EUen': 'strudel',
      'catch-EUde': 'gruaaa',
      'catch-EUes': 'ricitos',
      'catch-USes': 'achurf',
      'catch-EUfr': 'achtung',
      'catch-USfr': 'achtung',
      'catch-EUit': 'bailar',
      'catch-EUnl': 'strudel',
      'catch-CNzh': 'Over',
      'catch-TWzh': 'Over',
      'catch-JPja': 'オパー',
      'catch-KRko': '라저',
      'catch-EUru': 'штрудель',
    },
  },
  {
    id: 22,
    'file-name': 'bea15',
    name: {
      'name-USen': 'Megan',
      'name-EUen': 'Megan',
      'name-EUde': 'Dagmar',
      'name-EUes': 'Carmela',
      'name-USes': 'Carmela',
      'name-EUfr': 'Candy',
      'name-USfr': 'Candy',
      'name-EUit': 'Dolcinia',
      'name-EUnl': 'Megan',
      'name-CNzh': '糖果',
      'name-TWzh': '糖果',
      'name-JPja': 'キャンディ',
      'name-KRko': '캔디',
      'name-EUru': 'Меган',
    },
    personality: 'Normal',
    'birthday-string': 'March 13th',
    birthday: '13/3',
    species: 'Bear',
    gender: 'Female',
    subtype: 'A',
    hobby: 'Nature',
    'catch-phrase': 'sundae',
    icon_uri: 'https://acnhapi.com/v1/icons/villagers/22',
    image_uri: 'https://acnhapi.com/v1/images/villagers/22',
    'bubble-color': '#ec7efc',
    'text-color': '#fffce9',
    saying: "Take a page out of someone else's book, if it's a good book.",
    'catch-translations': {
      'catch-USen': 'sundae',
      'catch-EUen': 'sundae',
      'catch-EUde': 'lollipop',
      'catch-EUes': 'tutifruti',
      'catch-USes': 'tutifruti',
      'catch-EUfr': 'berlingot',
      'catch-USfr': 'berlingot',
      'catch-EUit': 'sucré',
      'catch-EUnl': 'lolly',
      'catch-CNzh': '舔舔',
      'catch-TWzh': '舔舔',
      'catch-JPja': 'ぺろ',
      'catch-KRko': '낼름',
      'catch-EUru': 'сладенько',
    },
  },
  {
    id: 23,
    'file-name': 'brd00',
    name: {
      'name-USen': 'Jay',
      'name-EUen': 'Jay',
      'name-EUde': 'Jan',
      'name-EUes': 'Jota',
      'name-USes': 'Jairo',
      'name-EUfr': 'Gérard',
      'name-USfr': 'Gérard',
      'name-EUit': 'Jet',
      'name-EUnl': 'Jay',
      'name-CNzh': '阿燕',
      'name-TWzh': '阿燕',
      'name-JPja': 'ツバクロ',
      'name-KRko': '참돌이',
      'name-EUru': 'Джей',
    },
    personality: 'Jock',
    'birthday-string': 'July 17th',
    birthday: '17/7',
    species: 'Bird',
    gender: 'Male',
    subtype: 'B',
    hobby: 'Fitness',
    'catch-phrase': 'heeeeeyy',
    icon_uri: 'https://acnhapi.com/v1/icons/villagers/23',
    image_uri: 'https://acnhapi.com/v1/images/villagers/23',
    'bubble-color': '#6b75ce',
    'text-color': '#9ae8df',
    saying: 'He who hesitates has lost.',
    'catch-translations': {
      'catch-USen': 'heeeeeyy',
      'catch-EUen': 'heeeeeyy',
      'catch-EUde': 'hiiiijjj',
      'catch-EUes': 'heeey',
      'catch-USes': 'eeey',
      'catch-EUfr': 'maaaaaais',
      'catch-USfr': 'maaaaaais',
      'catch-EUit': 'cipinci',
      'catch-EUnl': 'heeeeeyy',
      'catch-CNzh': '呢喃',
      'catch-TWzh': '呢喃',
      'catch-JPja': 'でおます',
      'catch-KRko': '그쵸',
      'catch-EUru': 'хей-хей',
    },
  },
  {
    id: 24,
    'file-name': 'brd01',
    name: {
      'name-USen': 'Robin',
      'name-EUen': 'Robin',
      'name-EUde': 'Jule',
      'name-EUes': 'Aria',
      'name-USes': 'Aria',
      'name-EUfr': 'Robie',
      'name-USfr': 'Robie',
      'name-EUit': 'Rossana',
      'name-EUnl': 'Robin',
      'name-CNzh': '喳喳',
      'name-TWzh': '喳喳',
      'name-JPja': 'パーチク',
      'name-KRko': '파틱',
      'name-EUru': 'Робин',
    },
    personality: 'Snooty',
    'birthday-string': 'December 4th',
    birthday: '4/12',
    species: 'Bird',
    gender: 'Female',
    subtype: 'B',
    hobby: 'Fashion',
    'catch-phrase': 'la-di-da',
    icon_uri: 'https://acnhapi.com/v1/icons/villagers/24',
    image_uri: 'https://acnhapi.com/v1/images/villagers/24',
    'bubble-color': '#6b75ce',
    'text-color': '#9ae8df',
    saying: 'Always keep your wings manicured so you can fly away.',
    'catch-translations': {
      'catch-USen': 'la-di-da',
      'catch-EUen': 'la-di-da',
      'catch-EUde': 'ladida',
      'catch-EUes': 'picatoste',
      'catch-USes': 'larará',
      'catch-EUfr': 'ta-di-da',
      'catch-USfr': 'ta-di-da',
      'catch-EUit': 'yuppidù',
      'catch-EUnl': 'lalala',
      'catch-CNzh': '喳',
      'catch-TWzh': '喳',
      'catch-JPja': 'さ',
      'catch-KRko': '글쎄',
      'catch-EUru': 'ля-ля-ля',
    },
  },
  {
    id: 25,
    'file-name': 'brd02',
    name: {
      'name-USen': 'Anchovy',
      'name-EUen': 'Anchovy',
      'name-EUde': 'Armin',
      'name-EUes': 'Boquerón',
      'name-USes': 'Boquerón',
      'name-EUfr': 'Miguel',
      'name-USfr': 'Miguel',
      'name-EUit': 'Acciuga',
      'name-EUnl': 'Anchovy',
      'name-CNzh': '凤尾',
      'name-TWzh': '鳳尾',
      'name-JPja': 'アンチョビ',
      'name-KRko': '안쵸비',
      'name-EUru': 'Анчоуи',
    },
    personality: 'Lazy',
    'birthday-string': 'March 4th',
    birthday: '4/3',
    species: 'Bird',
    gender: 'Male',
    subtype: 'B',
    hobby: 'Play',
    'catch-phrase': 'chuurp',
    icon_uri: 'https://acnhapi.com/v1/icons/villagers/25',
    image_uri: 'https://acnhapi.com/v1/images/villagers/25',
    'bubble-color': '#d86808',
    'text-color': '#fffce9',
    saying: 'Why do today what you can put off until tomorrow?',
    'catch-translations': {
      'catch-USen': 'chuurp',
      'catch-EUen': 'chuurp',
      'catch-EUde': 'tschurp',
      'catch-EUes': 'piu-piu',
      'catch-USes': 'piu-piu',
      'catch-EUfr': 'muf-muf',
      'catch-USfr': 'muf-muf',
      'catch-EUit': 'ciripì',
      'catch-EUnl': 'tsjiiirp',
      'catch-CNzh': '如斯',
      'catch-TWzh': '如斯',
      'catch-JPja': 'でシ',
      'catch-KRko': '이어라',
      'catch-EUru': 'чик-чирик',
    },
  },
  {
    id: 26,
    'file-name': 'brd03',
    name: {
      'name-USen': 'Twiggy',
      'name-EUen': 'Twiggy',
      'name-EUde': 'Twiggy',
      'name-EUes': 'Tití',
      'name-USes': 'Tití',
      'name-EUfr': 'Titi',
      'name-USfr': 'Titi',
      'name-EUit': 'Titti',
      'name-EUnl': 'Twiggy',
      'name-CNzh': '叽叽',
      'name-TWzh': '嘰嘰',
      'name-JPja': 'ピーチク',
      'name-KRko': '핀틱',
      'name-EUru': 'Твигги',
    },
    personality: 'Peppy',
    'birthday-string': 'July 13th',
    birthday: '13/7',
    species: 'Bird',
    gender: 'Female',
    subtype: 'B',
    hobby: 'Fashion',
    'catch-phrase': 'cheepers',
    icon_uri: 'https://acnhapi.com/v1/icons/villagers/26',
    image_uri: 'https://acnhapi.com/v1/images/villagers/26',
    'bubble-color': '#fff80d',
    'text-color': '#9b8986',
    saying: "It's the early bird that catches the worm!",
    'catch-translations': {
      'catch-USen': 'cheepers',
      'catch-EUen': 'cheepers',
      'catch-EUde': 'zwirtschi',
      'catch-EUes': 'tirití',
      'catch-USes': 'tirití',
      'catch-EUfr': 'coolos',
      'catch-USfr': 'coolos',
      'catch-EUit': 'ciiip',
      'catch-EUnl': 'fwieeet',
      'catch-CNzh': '叽',
      'catch-TWzh': '嘰',
      'catch-JPja': 'ッピ',
      'catch-KRko': '크',
      'catch-EUru': 'тю-вить',
    },
  },
  {
    id: 27,
    'file-name': 'brd04',
    name: {
      'name-USen': 'Jitters',
      'name-EUen': 'Jitters',
      'name-EUde': 'Alex',
      'name-EUes': 'Camelio',
      'name-USes': 'Camelio',
      'name-EUfr': 'Gilbert',
      'name-USfr': 'Gilbert',
      'name-EUit': 'Brivido',
      'name-EUnl': 'Jitters',
      'name-CNzh': '纪诺',
      'name-TWzh': '紀諾',
      'name-JPja': 'ジーニョ',
      'name-KRko': '딩요',
      'name-EUru': 'Джиттерс',
    },
    personality: 'Jock',
    'birthday-string': 'February 2nd',
    birthday: '2/2',
    species: 'Bird',
    gender: 'Male',
    subtype: 'B',
    hobby: 'Fitness',
    'catch-phrase': 'bzzert',
    icon_uri: 'https://acnhapi.com/v1/icons/villagers/27',
    image_uri: 'https://acnhapi.com/v1/images/villagers/27',
    'bubble-color': '#78dd62',
    'text-color': '#28665a',
    saying: "When you're a team of one, you're always captain!",
    'catch-translations': {
      'catch-USen': 'bzzert',
      'catch-EUen': 'bzzert',
      'catch-EUde': 'zischhh',
      'catch-EUes': 'pío-pío',
      'catch-USes': 'pío-pío',
      'catch-EUfr': 'bouerk',
      'catch-USfr': 'bouerk',
      'catch-EUit': 'bzzert',
      'catch-EUnl': 'tjulp',
      'catch-CNzh': '诺诺',
      'catch-TWzh': '諾諾',
      'catch-JPja': 'だニョ',
      'catch-KRko': '삼바',
      'catch-EUru': 'бзе-е-ерт',
    },
  },
  {
    id: 28,
    'file-name': 'brd05',
    name: {
      'name-USen': 'Piper',
      'name-EUen': 'Piper',
      'name-EUde': 'Iris',
      'name-EUes': 'Bárbara',
      'name-USes': 'Bárbara',
      'name-EUfr': 'Neige',
      'name-USfr': 'Neige',
      'name-EUit': 'Giuliva',
      'name-EUnl': 'Piper',
      'name-CNzh': '丽婷',
      'name-TWzh': '麗婷',
      'name-JPja': 'レイコ',
      'name-KRko': '파이프',
      'name-EUru': 'Пайпер',
    },
    personality: 'Peppy',
    'birthday-string': 'April 18th',
    birthday: '18/4',
    species: 'Bird',
    gender: 'Female',
    subtype: 'A',
    hobby: 'Play',
    'catch-phrase': 'chickadee',
    icon_uri: 'https://acnhapi.com/v1/icons/villagers/28',
    image_uri: 'https://acnhapi.com/v1/images/villagers/28',
    'bubble-color': '#ffffff',
    'text-color': '#848484',
    saying: "Where there's life, there's hope.",
    'catch-translations': {
      'catch-USen': 'chickadee',
      'catch-EUen': 'chickadee',
      'catch-EUde': 'tschikadii',
      'catch-EUes': 'chupiyá',
      'catch-USes': 'chupiyá',
      'catch-EUfr': 'puic puic',
      'catch-USfr': 'puic puic',
      'catch-EUit': 'cocoricò',
      'catch-EUnl': 'tjiep tjiep',
      'catch-CNzh': '山雀',
      'catch-TWzh': '山雀',
      'catch-JPja': 'けどー',
      'catch-KRko': '허나',
      'catch-EUru': 'чики-чик',
    },
  },
  {
    id: 29,
    'file-name': 'brd06',
    name: {
      'name-USen': 'Admiral',
      'name-EUen': 'Admiral',
      'name-EUde': 'Ansgar',
      'name-EUes': 'Avutardo',
      'name-USes': 'Avutardo',
      'name-EUfr': 'Maréchal',
      'name-USfr': 'Maréchal',
      'name-EUit': 'Adolfo',
      'name-EUnl': 'Admiral',
      'name-CNzh': '李彻',
      'name-TWzh': '李徹',
      'name-JPja': 'イッテツ',
      'name-KRko': '일섭',
      'name-EUru': 'Адмирал',
    },
    personality: 'Cranky',
    'birthday-string': 'January 27th',
    birthday: '27/1',
    species: 'Bird',
    gender: 'Male',
    subtype: 'A',
    hobby: 'Nature',
    'catch-phrase': 'aye aye',
    icon_uri: 'https://acnhapi.com/v1/icons/villagers/29',
    image_uri: 'https://acnhapi.com/v1/images/villagers/29',
    'bubble-color': '#0ca54a',
    'text-color': '#fffce9',
    saying: 'Only quitters give up.',
    'catch-translations': {
      'catch-USen': 'aye aye',
      'catch-EUen': 'aye aye',
      'catch-EUde': 'oh, ja',
      'catch-EUes': 'avechucho',
      'catch-USes': 'piuc-piuc',
      'catch-EUfr': 'cornichon',
      'catch-USfr': 'cornichon',
      'catch-EUit': 'cipissi',
      'catch-EUnl': 'yep yep',
      'catch-CNzh': '贯彻',
      'catch-TWzh': '貫徹',
      'catch-JPja': 'ってか',
      'catch-KRko': '오예',
      'catch-EUru': 'чиф-чиф',
    },
  },
  {
    id: 30,
    'file-name': 'brd08',
    name: {
      'name-USen': 'Midge',
      'name-EUen': 'Midge',
      'name-EUde': 'Anna',
      'name-EUes': 'Paloma',
      'name-USes': 'Paloma',
      'name-EUfr': 'Michèle',
      'name-USfr': 'Michèle',
      'name-EUit': 'Minù',
      'name-EUnl': 'Midge',
      'name-CNzh': '小酒窝',
      'name-TWzh': '小酒窩',
      'name-JPja': 'うずまき',
      'name-KRko': '핑글이',
      'name-EUru': 'Мидж',
    },
    personality: 'Normal',
    'birthday-string': 'March 12th',
    birthday: '12/3',
    species: 'Bird',
    gender: 'Female',
    subtype: 'B',
    hobby: 'Education',
    'catch-phrase': 'tweedledee',
    icon_uri: 'https://acnhapi.com/v1/icons/villagers/30',
    image_uri: 'https://acnhapi.com/v1/images/villagers/30',
    'bubble-color': '#ec7efc',
    'text-color': '#fffce9',
    saying: 'When the world gets cold, just fly south.',
    'catch-translations': {
      'catch-USen': 'tweedledee',
      'catch-EUen': 'tweedledee',
      'catch-EUde': 'twitiriti',
      'catch-EUes': 'arrurrú',
      'catch-USes': 'arrurrú',
      'catch-EUfr': 'loulou',
      'catch-USfr': 'loulou',
      'catch-EUit': 'firulì',
      'catch-EUnl': 'kwetter',
      'catch-CNzh': '脸红',
      'catch-TWzh': '臉紅',
      'catch-JPja': 'キョン',
      'catch-KRko': '핑그르르',
      'catch-EUru': 'тви-тви',
    },
  },
  {
    id: 31,
    'file-name': 'brd11',
    name: {
      'name-USen': 'Jacob',
      'name-EUen': 'Jakey',
      'name-EUde': 'Jesko',
      'name-EUes': 'Repollo',
      'name-USes': 'Repollo',
      'name-EUfr': 'Jacob',
      'name-USfr': 'Jacob',
      'name-EUit': 'Valerio',
      'name-EUnl': 'Jacob',
      'name-CNzh': '余板',
      'name-TWzh': '余板',
      'name-JPja': 'ジャコテン',
      'name-KRko': '야곱',
      'name-EUru': 'Джейкоб',
    },
    personality: 'Lazy',
    'birthday-string': 'August 24th',
    birthday: '24/8',
    species: 'Bird',
    gender: 'Male',
    subtype: 'A',
    hobby: 'Nature',
    'catch-phrase': 'ya feel',
    icon_uri: 'https://acnhapi.com/v1/icons/villagers/31',
    image_uri: 'https://acnhapi.com/v1/images/villagers/31',
    'bubble-color': '#ffffff',
    'text-color': '#848484',
    saying: 'Your greatest strength can be your greatest weakness.',
    'catch-translations': {
      'catch-USen': 'ya feel',
      'catch-EUen': 'ya feel',
      'catch-EUde': 'tirilü',
      'catch-EUes': 'pelusilla',
      'catch-USes': 'chiurp',
      'catch-EUfr': 'asticô',
      'catch-USfr': 'asticô',
      'catch-EUit': 'ciiipito',
      'catch-EUnl': 'snappie',
      'catch-CNzh': '话说',
      'catch-TWzh': '話說',
      'catch-JPja': 'っつーの',
      'catch-KRko': '그거야',
      'catch-EUru': 'чуррп',
    },
  },
  {
    id: 32,
    'file-name': 'brd15',
    name: {
      'name-USen': 'Lucha',
      'name-EUen': 'Lucha',
      'name-EUde': 'Lukas',
      'name-EUes': 'Plumerio',
      'name-USes': 'Plumerio',
      'name-EUfr': 'Condor',
      'name-USfr': 'Condor',
      'name-EUit': 'Loreto',
      'name-EUnl': 'Lucha',
      'name-CNzh': '摔角鸦',
      'name-TWzh': '摔角鴉',
      'name-JPja': 'マスカラス',
      'name-KRko': '마스카라스',
      'name-EUru': 'Луча',
    },
    personality: 'Smug',
    'birthday-string': 'December 12th',
    birthday: '12/12',
    species: 'Bird',
    gender: 'Male',
    subtype: 'A',
    hobby: 'Fitness',
    'catch-phrase': 'cacaw',
    icon_uri: 'https://acnhapi.com/v1/icons/villagers/32',
    image_uri: 'https://acnhapi.com/v1/images/villagers/32',
    'bubble-color': '#ff4040',
    'text-color': '#fffad4',
    saying: 'Birds of a feather, et cetera, et cetera...',
    'catch-translations': {
      'catch-USen': 'cacaw',
      'catch-EUen': 'cacaw',
      'catch-EUde': 'mauser',
      'catch-EUes': 'picopico',
      'catch-USes': 'pío',
      'catch-EUfr': 'yaaaah',
      'catch-USfr': 'yaaaah',
      'catch-EUit': 'lorito',
      'catch-EUnl': 'kakauw',
      'catch-CNzh': '嘎',
      'catch-TWzh': '嘎',
      'catch-JPja': 'カァー',
      'catch-KRko': '까아악',
      'catch-EUru': 'кар-ко',
    },
  },
  {
    id: 33,
    'file-name': 'brd16',
    name: {
      'name-USen': 'Jacques',
      'name-EUen': 'Jacques',
      'name-EUde': 'Pierre',
      'name-EUes': 'Gorrelmo',
      'name-USes': 'Gorrelmo',
      'name-EUfr': 'Jacky',
      'name-USfr': 'Jacky',
      'name-EUit': 'Zampiero',
      'name-EUnl': 'Jacques',
      'name-CNzh': '赵奇',
      'name-TWzh': '趙奇',
      'name-JPja': 'ジョッキー',
      'name-KRko': '쪼끼',
      'name-EUru': 'Жак',
    },
    personality: 'Smug',
    'birthday-string': 'June 22nd',
    birthday: '22/6',
    species: 'Bird',
    gender: 'Male',
    subtype: 'A',
    hobby: 'Music',
    'catch-phrase': 'zut alors',
    icon_uri: 'https://acnhapi.com/v1/icons/villagers/33',
    image_uri: 'https://acnhapi.com/v1/images/villagers/33',
    'bubble-color': '#194c89',
    'text-color': '#fffad4',
    saying: 'Better to have loved and squawked than to have never loved at all.',
    'catch-translations': {
      'catch-USen': 'zut alors',
      'catch-EUen': 'zut alors',
      'catch-EUde': 'piepiep',
      'catch-EUes': 'chapó',
      'catch-USes': 'chapó',
      'catch-EUfr': 'ploc ploc',
      'catch-USfr': 'why not',
      'catch-EUit': 'pio pio',
      'catch-EUnl': 'zut alors',
      'catch-CNzh': '唷唷唷',
      'catch-TWzh': '唷唷唷',
      'catch-JPja': 'チェケラ',
      'catch-KRko': '체키라웃',
      'catch-EUru': 'фу ты',
    },
  },
];

const server = setupServer(
  rest.get('https://acnhapi.com/v1a/villagers', (req, res, ctx) => {
    return res(ctx.json(mockResponse));
  })
);

beforeAll(() => server.listen());

afterAll(() => server.close());

test('renders villagers', async () => {
  render(<Home />);
  const vName = await screen.findByText(/cyrano/i);
  expect(vName).toBeInTheDocument();
});

test('renders welcome home on home page', () => {
  render(<Home />);

  const welcome = screen.getByText(/welcome home/i);
  expect(welcome).toBeInTheDocument();
});

test('select box works', async () => {
  render(<Home />);

  const dropdown = await screen.findByRole('combobox');
  userEvent.selectOptions(dropdown, 'Villagers');
  expect(screen.getByRole('option', { name: /villagers/i }).selected).toBe(true);
});
